### ISSUE TITLE
Adjusting the origin on objects

### ISSUE THREAD

**Issue by oscar-broman** [samp-incognito/samp-streamer-plugin#103]
Many buildings have the origin far from their middle, which makes them stream in quicker on one side than on the other.

It would be useful to be able to modify the center position on objects to avoid this problem.

**Comment by Crayder** [comment]
This would be amazing! Even if streamer just used the centers internally that'd be great.

The centers are perfect in ColAndreas (well, for the collision meshes), so you could use the data from that. I already have it in my model sizes include.

**Comment by samp-incognito** [comment]
This could be done.

**Comment by Southclaw** [comment]
Setting object origin for rotations would also be super handy, though probably out of the scope for the streamer.

**Comment by samp-incognito** [comment]
Well, that wouldn't be hard to add either, actually, but I'm having trouble thinking of a way it could be useful.

**Comment by Crayder** [comment]
Ex. Streaming objects from their actual center instead of their offset. A building being streamed from it's corner instead of it's center. What if I'm on the other side of that building (the side opposite of the one with that corner)? The stream distance could be off by a lot. This would be a solution.

There are much worse situations, but that's the first example that comes to mind.

**Comment by Southclaw** [comment]
As for the rotation thing this is very useful for wall/door type objects that may not have an origin where you want it, so rotating about a corner would be very useful if the object itself doesn't have the origin at the edge you want to rotate about.

The reason I mentioned this here was because I develop a gamemode largely centred around construction and this is something I was going to implement however having this feature available at the *object-level* rather than the *constructable object-level* seems like a logical choice. Like I said though, it might be out of scope for the streamer so I might just develop this as an object-wrapper library in Pawn.

**Comment by Crayder** [comment]
@Southclaw For that particular use you could check out Texture Studio's pivot system.

And that brings up another example for a way this could be used. Say I have a giant map that I want to rotate around a specific point, doing all of the math in PAWN sucks ass. Texture Studio is my witness. So I could just use this to replace Texture Studio's pivot system.

**Comment by Southclaw** [comment]
@Crayder what I was referring to was an API-level method to do it in code rather than a tool to edit objects. I'll likely write a wrapper script for it or if I work on this original issue, I'll just add that functionality into the pull request if Incognito is okay with that.

**Comment by Crayder** [comment]
Yeah I know that's what you meant. I support that 100%. I was just tossing up another example of why it'd be useful since Incognito still can't find usefulness.
