### ISSUE TITLE
3d labels

### ISSUE THREAD

**Issue by Sylvain38** [samp-incognito/samp-streamer-plugin#115]
Hello Incognito,

We currently have some weird bug with your streamer when we used the streamed 3d text labels features. Indeed 5 minutes after the server start, the labels are mixed up.

This bug does not occur when we use normal (not streamed) labels, so I think the bug is from your plugin, which is working perfect for all other stuff :)

**Comment by IstuntmanI** [comment]
I have no problems with them. You should also test them in an empty server, it may be a problem from your code. If it is still not working, could you give us a simple script to reproduce it ?

**Comment by Sylvain38** [comment]
Well I can show you the bug on our server (GamerX). We spent many days to try to fix it and it's still occuring. What is your GMT ? Are you available this evening ?

**Comment by IstuntmanI** [comment]
You are probably just saving their IDs in a variable and when you delete it you forget to reset that variable, or something like that. I don't need to see it. The idea is that 3DTexts are working fine in the Streamer Plugin.

**Comment by Sylvain38** [comment]
Thanks you for trying to help me. No I don't forget to reset the id every time I delete a label I set it to "3DText=0". I will try to remake the whole code and I will come back if it still bugged. Thanks again for your help it's appreciated.

**Comment by samp-incognito** [comment]
Unfortunately, without a way to reproduce it, there's not a whole lot I can do. I think someone from GamerX (maybe it was you or Matite) contacted me about this a while ago, but I've since looked over the code and really just can't find anything wrong it. Additionally, I don't know why attached 3D text labels would be affected and nothing else since almost all of the logic is shared across the different streaming algorithms (for example, I would expect the same problem to occur with attached areas, but those work perfectly fine).

I do know there was once a problem with 3D text labels in SA-MP that was similar to this bug. I don't know if it was ever fixed. I can't find much information about it on the forums. Maybe someone else knows more. If that's the case, though, then there really is nothing I can do about it. You could try reattaching the labels automatically to ensure they're attached to the correct players.
