### ISSUE TITLE
Objects disappearing

### ISSUE THREAD

**Issue by Aluminium-1** [samp-incognito/samp-streamer-plugin#121]
I have 6693 CreateDynamicObjects loaded into my gamemode. I have a furniture system that allows players to place furnitures into interiors and edit their position. However, as new furniture is added, the server despawns some other pieces of furniture which is loaded from the database. I have been told that there might be limitations with the plugin so I would like to know if it is a problem with the streamer, or the specifications of my server or if it is even a SAMP problem. Help will be highly appreciated.

**Comment by Southclaw** [comment]
Dynamic objects are allocated dynamically so there is no technical limit, even a low end server should handle much more than 6000 objects (each object is only a few bytes as far as I can remember anyway, give or take the complexities of the indexing system). I've never noticed anything like this on my project (which is creating and destroying items *constantly*) although I do use an older version.

I'm not sure if having normal CreateObject objects can cause this but either way that should be avoided anyway in favour of static `CreateDynamicObject`s.

**Comment by Patrik356b** [comment]
There is still a client limit of how much objects you can create at the same time in the same area. 

Normally you shouldn't hit this limited, but it depends on how close they are to each other

**Comment by Zunno** [comment]
Well i got 2910 Objects and i have the same Problem. Just added ~200 Objects the last days.

**Comment by IstuntmanI** [comment]
By "despawning" you mean that they are being automatically DESTROYED ? I use the Streamer Plugin since few years ago and I can surely tell you that it has no problem like that. Also, it can support even 1.000.000 elements without any problem (well, if you have 512mb RAM it may be a problem, as their informations are stored in the dynamic memory). But if you mean that they are starting to disappear when you get farther:

I never had a problem with the visibility of streamed objects. Also, when someone requested my help because they had a problem like this and I helped them I saw that the main reasons were:
1. They used too many CreateObject/CreatePlayerObject by default. Streamer Plugin uses CreatePlayerObject internally and SA:MP's limit is 1000 objects created at once (counted with CreateObject too). So if you have 600 CreateObject in your script and 395 CreatePlayerObject, Streamer Plugin will only be able to show you only 5 more objects.
2. They had maps which had way too many objects, so they needed to increase the limit from Streamer_SetVisibleItems.

Make sure to check what I said. Also, if you still don't find the solution, try to provide us an example code (a not-too-long code with the reproduction of the bug), so we could test.

**Comment by Zunno** [comment]
I dont really use CreateObject. Maybe just for RoadBlocks or Bombs. But its always under 10. So the  Streamer has 490 to display. But 2 days ago i had that my Bank disappeard.. Only 10 objects and the burger shot nord is near the area but also not more than 60.
So thats 70 objects in this area... and its for all players. If i recreated them its just fine. My Objects are created in a filterscript. Never had problems with that.

**Comment by samp-incognito** [comment]
Indeed, there is no imposed limit on the amount of dynamic objects that can be created, but the plugin is still bound by a finite number of player objects that can be shown at once. (This is is set to 500 by default, and it can be increased with Streamer_SetVisibleItems, but this will also increase the load on the server.) You'll need to adjust the streaming distances to ensure the limit isn't reached. You could also take advantage of some of the newer features, like per-object areas and priorities.

Anyway, this isn't a problem with the plugin. I'd suggest searching the forums and some of the existing issues here for further discussion on it.
