### ISSUE TITLE
Streamer_GetIntData

### ISSUE THREAD

**Issue by NegativeIQ** [samp-incognito/samp-streamer-plugin#131]
Streamer_GetIntData(STREAMER_TYPE_OBJECT, objectid, E_STREAMER_PLAYER_ID)
Note: E_STREAMER_PLAYER_ID

It returns 0 if its a global dynamic object (not per player based). But 0 is a valid player...

**Comment by IstuntmanI** [comment]
E_STREAMER_PLAYER_ID is default at -1, which means { 0, 1, 2, ... 1000 }. So Streamer_GetIntData gets the first player in array. It is like that in case you have only one player for an object and you want to simply use Streamer_GetIntData instead of Streamer_GetArrayData.

**Comment by NegativeIQ** [comment]
Isnt E_STREAMER_PLAYER_ID supposed to return playerid for which given item (object in these case) was created?

Like if i create 5 global objects (playerid -1) and sixth is for playerid 3, and i use 6 for objectid in Streamer_GetIntData (example from first post) it should return 3 (since that object is only visible by playerid 3), while for first five it should return INVALID_PLAYER_ID or at least -1 since everyone can see that objects.

**Comment by IstuntmanI** [comment]
Yes, it is supposed to. It does, if you use Streamer_GetArrayData. If you use Streamer_GetIntData it only returns the first value from the E_STREAMER_PLAYER_ID vector (-1 fills all player IDs slots with valid player IDs, so the first one is 0).

Yes, that's what it will return for the sixth. For the first five it returns 0 because the vector is { 0, 1, 2, ... 1000 } not only { -1 }. I tested it before and this is how it handles it.

**Comment by Crayder** [comment]
Actually if I recall correctly it works like this...

```pawn
new data[2];
Streamer_GetArrayData(STREAMER_TYPE_OBJECT, objectid, E_STREAMER_PLAYER_ID, data, sizeof data)
```

If the objects were like this (player ID set in CreatDynamicObject):

Object ID | Player ID
-------------------------------
0 | -1
1 | -1
2 | 13
3 | 7
4 | -1

Then in `data` for (notice the object ID):

> Streamer_GetArrayData(STREAMER_TYPE_OBJECT, 0, E_STREAMER_PLAYER_ID, data, sizeof data)

Would be [0] 0 and [1] 1 (and so on if you have a different sized `data`, [2] 2 and [n] n), the same goes for object 1 and 4 because they are also global.

For either object 2 or 3 the stuff in `data` will all be the player ID.

**Comment by IstuntmanI** [comment]
AFAIK, in a recent update Incognito made it possible to use **Streamer_GetIntData** for E_STREAMER_PLAYER_ID too, only that it would get only the first value in the container, which would be 0 for a virtual world of { -1 }.

**Comment by samp-incognito** [comment]
@IstuntmanI is right about how this works. When you use Streamer_GetIntData with E_STREAMER_PLAYER_ID, it will just return the first bit that is set in the player bit array. That's why it's returning 0 for you. I suppose it would make more sense to return -1 if every bit is set, though, so I'll fix that.

**Comment by NegativeIQ** [comment]
Thank you both for giving attention to these issue of mine. I will be waiting for "fix" or should i say modification since its just misunderstanding from my side on how the system works.
