### ISSUE TITLE
Stream Vehicles

### ISSUE THREAD

**Issue by alxndrr** [samp-incognito/samp-streamer-plugin#138]
Who know how to stream vehicles? (It's possible?)

And will be this feature in this plugin?

**Comment by IstuntmanI** [comment]
Streaming vehicles is way way harder, because they got lots of functions and callbacks. Also, SA:MP already provides an internal vehicle streamer. So a streamer for a streamer is harder to make.

kurta999 already attempted this, but I saw some feedbacks that it is buggy: https://github.com/kurta999/samp-streamer-plugin . Incognito may be able to finish it, but I don't think he has enough time for it, it also requires a lot of testing.

**Comment by samp-incognito** [comment]
This indeed isn't likely to happen for the reasons stated above. I know that kurta999 started on this, but it seems he's no longer around, sadly, and I don't think it was well tested. Anyone else is welcome to continue his work, but I don't have the time for it, unfortunately.

**Comment by rt-2** [comment]
I don't think it's possible.
Object streamers use the "per player" limits, but there is no "per player" vehicles, only global.
