### ISSUE TITLE
Editing dynamic objects

### ISSUE THREAD

**Issue by roun512** [samp-incognito/samp-streamer-plugin#147]
When I try to edit a global Dynamic object using EditDynamicObject it updates only for the playerid supplied, not for everyone..

Shouldn't [this](https://github.com/samp-incognito/samp-streamer-plugin/blob/master/src/natives/objects.cpp#L558) be `sampgdk::EditObject(p->first, internalID);` instead?

Also SelectDynamicObject is missing or?

**Comment by IstuntmanI** [comment]
You have to use the OnPlayerEditDynamicObject to let it update to others. It is called when the object is being edited (position/rotation being changed) or when you cancel/save the edit.
edited (position/rotation being changed) or when you cancel/save the edit.
http://wiki.sa-mp.com/wiki/OnPlayerEditObject

Streamer Plugin relies on PLAYER objects, not on global objects, this is why it has EditPlayerObject instead of EditObject. Global objects have a global limit of 1000, but player objects have a limit of 1000 per player, so with player objects you can show different objects to different players, based on what they need.
http://wiki.sa-mp.com/wiki/Limits

There's no need for SelectDynamicObject. It is just a client-sided action of selecting a SA-MP object. When a player selects an object it calls OnPlayerSelectObject, if it is a player object it has the type parameter set to 2 (SELECT_OBJECT_PLAYER_OBJECT), then the streamer hooks it and cancels further callback calling in the gamemode, calling OnPlayerSelectDynamicObject instead.
http://wiki.sa-mp.com/wiki/SelectObject
http://wiki.sa-mp.com/wiki/OnPlayerSelectObject
