### ISSUE TITLE
Not all Pickups/3dLabels seem to be streamed / Pickups hinder plugin to stream objects

### ISSUE THREAD

**Issue by Bios-Marcel** [samp-incognito/samp-streamer-plugin#166]
Hey,

I do have a racing map, it has about 4623 objects, 66 pickups and about 66 3dlabels. I don't know why, but specific pickups are not being streamed.

I created a gist of the code, if thats any help: https://gist.github.com/Bios-Marcel/71fcdf9223399027d099260c23eac6b9 

greetings Marcel

**Comment by IstuntmanI** [comment]
Well, this may be due to a SA-MP bug. Pickups of some type (most of the types AFAIK) that are created on custom objects ( CreatePlayerObject(/CreateDynamicObject)/CreateObject ) or in air aren't being shown at all. Try to use CreatePickup and see if it is indeed a SA-MP bug.

**Comment by Bios-Marcel** [comment]
I am using the same type at all pickups (1247 / 1)
Also, i switched to Dynamic pickup since the streamer stopped working when i used normal text labels or pickups.

**Comment by Bios-Marcel** [comment]
Update: I don't use pickups anymore, i have switched to labels, but now the same thing happens with those, if i remove em i can the objects

**Comment by samp-incognito** [comment]
It just sounds like a scripting issue. You probably have an array going out of bounds while creating the pickups that's preventing the rest of them from being created as well.

What's the size of `pickupInfo` in that code? If it's not big enough to accommodate all of the pickups, then there's your problem.

**Comment by Bios-Marcel** [comment]
Oh, you are right, it is 104 pickups and an array size of 100, i am so sorry, i am a douche

**Comment by IstuntmanI** [comment]
You should use crashdetect: https://github.com/Zeex/samp-plugin-crashdetect.

Also, don't store informations about streamer item IDs in a dimension of a pawn array because streamer can have an unlimited number of items. Instead, you could use Streamer's EXTRA_ID and learn to store them in another way.

**Comment by Bios-Marcel** [comment]
Na, the EXTRA_ID isn't enough, i need to save up to 5 things (+ position(3))

**Comment by IstuntmanI** [comment]
Well, there are even more ways to store them better. My favourite way is something like this, for your case, if they aren't dynamically created:
```pawn
new labelText[ 40 ];

enum geVehiclePickups
{
	type,
	Float:X,
	Float:Y,
	Float:Z,
	vehicleID,
};

new gaVehiclePickups[ ][ geVehiclePickups ] =
{
	{ PICKUP_TYPE_NITRO, 5.0, 5.0, 5.0 }, // vehicleID will default to 0
	{ PICKUP_TYPE_VEHICLE, 5.0, 5.0, 5.0, 5 },
	{ PICKUP_TYPE_REPAIR, 5.0, 5.0, 5.0 } // vehicleID will default to 0
};

new gaVehiclePickupsItems[ sizeof gaVehiclePickups ][ 2 ]; // Pickup and 3DLabelLabel

public OnFilterScriptInit( )
{
	for( new i = 0; i < sizeof gaVehiclePickups; i ++ )
	{
	    gaVehiclePickupsItems[ i ][ 0 ] = _:CreateDynamicPickup( 1247, 1, gaVehiclePickups[ i ][ X ], gaVehiclePickups[ i ][ Y ], gaVehiclePickups[ i ][ Z ], -1, _, _, _, _, 1 );

		switch( gaVehiclePickups[ i ][ type ] )
		{
			case PICKUP_TYPE_VEHICLE:
			{
				format( labelText, 40, "Vehicle Pickup\n%s", getVehicleNameByModelID( gaVehiclePickups[ i ][ vehicleID ] ) );
				gaVehiclePickupsItems[ i ][ 1 ] = _:CreateDynamic3DTextLabel( labelText, 0x008080FF, gaVehiclePickups[ i ][ X ], gaVehiclePickups[ i ][ Y ], gaVehiclePickups[ i ][ Z ], 150.0 );
			}

			case PICKUP_TYPE_NITRO: gaVehiclePickupsItems[ i ][ 1 ] = _:CreateDynamic3DTextLabel( "Nitro Pickup", 0x008080FF, gaVehiclePickups[ i ][ X ], gaVehiclePickups[ i ][ Y ], gaVehiclePickups[ i ][ Z ], 150.0 );

			case PICKUP_TYPE_REPAIR: gaVehiclePickupsItems[ i ][ 1 ] = _:CreateDynamic3DTextLabel( "Repair Pickup", 0x008080FF, gaVehiclePickups[ i ][ X ], gaVehiclePickups[ i ][ Y ], gaVehiclePickups[ i ][ Z ], 150.0 );
		}
	}
	return 1;
}
```

If you also want to create them dynamically, using GVar plugin would be better than your way, or a STL container.

Why your way is bad ? Because, as I said, streamer plugin can provide a really big number of item IDs, so you won't be able to create an array of main size 500_000 just to store some items between ID 499_995 and 499_999 (well, just an exaggerated example). Also, your stored items from that array may skip few IDs if in between them are created some other items from other parts of your server, leaving a lot of the array empty.

When you are doing something should stick to the best methods, without using very error prone methods like your code from that gist.

I hope you get what I said.
