### ISSUE TITLE
AttachDyn3DTextLabelToPlayer & AttachDyn3DTextLabelToVehicle

### ISSUE THREAD

**Issue by NexiusTailer** [samp-incognito/samp-streamer-plugin#169]
Hey. Working with streamer's 3D texts I faced a problem: during the game I need to be able attach label to car first, then to player or backward. I wouldn't want to recreate it every time, because it inconvenient, also particularly because default labels already have those functions.

**Comment by IstuntmanI** [comment]
Use
```pawn
native Streamer_SetIntData(type, STREAMER_ALL_TAGS id, data, value);
```
Example:
```pawn
Streamer_SetIntData(STREAMER_TYPE_3D_TEXT_LABEL, myLabel, E_STREAMER_ATTACHED_PLAYER, playerid);
```

Also, note that you can't specify offsets for the attached dynamic 3DTextLabels, because internally they are based on CreatePlayer3DTextLabel (which has the attached player/vehicle in the creation function, without offsets), not on Create3DTextLabel (with the separate function Attach3DTextLabelToPlayer which has offsets).

**Comment by NexiusTailer** [comment]
Thanks a lot, but I still don't understand why not to add a separate function... It would be very useful.

**Comment by samp-incognito** [comment]
Well, there are several things that can only be modified through the data manipulation natives. It's easier to do this than add hundreds of other natives that do basically the same thing. The reason these particular ones have never been added is because there aren't any standalone player 3D text natives for attaching players/vehicles.

Just use `Streamer_SetIntData` and also `Streamer_SetFloatData` if you want to modify the position (or offsets when attached).
