### ISSUE TITLE
Issue with EditDynamicObject after an object has been created

### ISSUE THREAD

**Issue by TommyB123** [samp-incognito/samp-streamer-plugin#176]
In this video below you will find me using two different systems with both 2.9.0 and 2.8.2, except 2.8.2 works properly and 2.9.0 does not. The code remains identical in both tests.

[![help](https://img.youtube.com/vi/TtPNeB0LIy0/0.jpg)](https://www.youtube.com/watch?v=TtPNeB0LIy0)

**Comment by samp-incognito** [comment]
Try [samp-streamer-plugin-2.9.0-test-2.zip](https://github.com/samp-incognito/samp-streamer-plugin/releases/download/v2.9.0/samp-streamer-plugin-2.9.0-test-2.zip).

This is related to how objects are streamed in chunks in v2.9.0, though I've changed it just now so that Streamer_Update(Ex) functions as it did before. You'll need to use one of those before EditDynamicObject for this to work properly.

**Comment by TommyB123** [comment]
The fix does not seem to work. I'm still getting the same results shown in my video even after ensuring ```Streamer_Update``` is called after creating the object and before editing it.

**Comment by samp-incognito** [comment]
Could you try redownloading?

**Comment by TommyB123** [comment]
Seems to be fixed now. Thank you very much!
