### ISSUE TITLE
OnVehicleEnterDynamicArea?

### ISSUE THREAD

**Issue by OwlIT** [samp-incognito/samp-streamer-plugin#180]
I can't find any method to instantly detect if a vehicle enters in a dynamic area. I was thinking about IsPointInAnyDynamicArea and constantly get the vehicle's coord but I don't think it's a good decision.

**Comment by Southclaws** [comment]
If the vehicle is occupied you can use the player event, it's accurate enough. Otherwise, tracking unoccupied vehicles tend to be inaccurate and depending on the amount of vehicles, process intensive. You could use `OnUnoccupiedVehicleUpdate` in combination with other checks to narrow down the amouny of vehicles you're actually checking.

**Comment by OwlIT** [comment]
For "player event" do you mean OnPlayerEnterDynamicArea? Because it won't get called if a player is inside a vehicle. 
Area example:
`HouseInfo[id][hEnterArea] = CreateDynamicSphere(HouseInfo[id][hEnterX], HouseInfo[id][hEnterY], HouseInfo[id][hEnterZ], 1.5, HouseInfo[id][hVW], HouseInfo[id][hEnterInt]);
Streamer_SetIntData(STREAMER_TYPE_AREA, HouseInfo[id][hEnterArea], E_STREAMER_EXTRA_ID, id + HOUSE_MAGIC);`

**Comment by OwlIT** [comment]
Up

**Comment by samp-incognito** [comment]
> For "player event" do you mean OnPlayerEnterDynamicArea? Because it won't get called if a player is inside a vehicle.

It does get called for players in vehicles.

**Comment by Southclaws** [comment]
I *think* the position checked is the player's model position in the vehicle, so there is an inherent offset to the left that always applies (I *think* this is the case, I can't actually remember).

If that is the case, and you want the check to incorporate the vehicle null-point instead of the player's then the simple solution would be to:

1. make the streamer area a bit bigger, big enough so that if, with the original size, the vehicle would land in the area and the player wouldn't, the slightly larger size would compensate.
2. on the entry event, grab the player's vehicle ID
3. check the distance between the vehicle ID and your area centrepoint, if it's in range, run your desired code.

Beats implementing a whole new callback for vehicles. Unless this case is already covered by the streamer and it actually checks the player's vehicle position *if* they are in one - in which case ignore what I said :)

**Comment by samp-incognito** [comment]
Only the player's position is checked. The vehicle's position could be checked when necessary, I guess, though I don't know if the difference would be significant enough to matter in most cases.
