### ISSUE TITLE
Streamer_ToggleItemInvAreas

### ISSUE THREAD

**Issue by AbyssMorgan** [samp-incognito/samp-streamer-plugin#197]
Function Streamer_ToggleItemInvAreas not working, objects is always visible outside/inside area.

**Comment by IstuntmanI** [comment]
You closed this by mistake ? (looks like you closed this one minute after the issue was created)

If yes: @Crayder [suggested this feature](https://github.com/samp-incognito/samp-streamer-plugin/issues/111), so I guess that he uses inverse areas. Is it working correctly for you ? (I'm not using this feature)

**Comment by AbyssMorgan** [comment]
I created this by mistake, thinking that function does not work, but it turned out that it worked properly.
