### ISSUE TITLE
Idea for polygons

### ISSUE THREAD

**Issue by continue98** [samp-incognito/samp-streamer-plugin#211]
Hi. I suggest adding rendering polygons line. Here is example: [`screen`](https://vgy.me/mIc7OT.png)
`SetRendringLinePolygon(polygon_id, color_line, size_line)`

**Comment by IstuntmanI** [comment]
This isn't streamer's job. Also, it can't be made too easy because we have to use [gangzones](http://wiki.sa-mp.com/wiki/GangZoneCreate) which aren't too flexible. For every change of direction of a polygon line we would need another gangzone, but there's a [pretty low limit](http://wiki.sa-mp.com/wiki/Limits) for them, so we couldn't have too much advanced polygons lines.

It is better to create your own method for this, streamer doesn't have anything related to gangzones ([at least yet](https://github.com/samp-incognito/samp-streamer-plugin/issues/177), but I don't think there will ever be a gangzone streamer in this plugin, at least not until SA-MP adds per-player gangzones, which I doubt, as it looks pretty dead and per-player pickups are needed more than per-player gangzones).

**Comment by continue98** [comment]
Polygons already exist in the streamer, but why not make an optional drawing of these lines?
It would be extremely useful

**Comment by Southclaws** [comment]
The streamer's job is to stream. Not render stuff.
If you want to do this, write a filterscript to do it. It doesn't require any plugin code because all the data is available via Pawn functions (polygon coordinates).

**Comment by samp-incognito** [comment]
I would agree that this is outside the scope of the streamer.
