### ISSUE TITLE
BUG:OnPlayerEnterDynamicArea & OnPlayerLeaveDynamicArea

### ISSUE THREAD

**Issue by energizer1337** [samp-incognito/samp-streamer-plugin#229]
Does not work OnPlayerEnterDynamicArea if you move the player (SetPlayerPos)

**Comment by IstuntmanI** [comment]
If the player won't move it won't be called. You need to enable ```Streamer_ToggleIdleUpdate```.

**Comment by energizer1337** [comment]
Does not work if you move a player from one zone to another

**Comment by IstuntmanI** [comment]
It works perfectly fine for me. You are probably handling the callbacks wrong or you did other mistakes. I suggest you to ask about this problem on forum in the official Streamer Plugin (topic)[http://forum.sa-mp.com/showthread.php?t=102865] because this is for sure not a problem with the Streamer, I use lots of areas in my server with no problems like what you described. Also, on GitHub issues you should create only good suggestions and real problems of the project, for scripting help you have the forum.

This should be closed.

**Comment by energizer1337** [comment]
No, apparently you misunderstood, when moving a player from one area to another, sometimes works OnPlayerEnterDynamicArea and after him OnPlayerLeaveDynamicArea.

In terms of code, everything is fine.
`public OnPlayerEnterDynamicArea(playerid, areaid) {
    SendClientMessage(playerid, -1, "OnPlayerEnterDynamicArea");
    return 1;
}
public OnPlayerLeaveDynamicArea(playerid, areaid) {
    SendClientMessage(playerid, -1, "OnPlayerLeaveDynamicArea");
    return 1;
}`

**Comment by IstuntmanI** [comment]
Well, exactly what I said. You handle the code wrong. Area enter/exit callbacks aren't called in order everytime. It depends on their ID and priority if I remember correctly.

**Comment by energizer1337** [comment]
But after all, when moving with `SetPlayerPos`, `OnPlayerLeaveDynamicArea` should initially work.

**Comment by IstuntmanI** [comment]
Oh, well, ```OnPlayerLeaveDynamicArea``` will be called anyway, it does for me. Here's how it is being handled:
- Discovering that the player entered/left the area:

https://github.com/samp-incognito/samp-streamer-plugin/blob/f49065baa5e2360170cd36a1115512b778523a73/src/streamer.cpp#L783-L802
- Calling the callbacks:

https://github.com/samp-incognito/samp-streamer-plugin/blob/f49065baa5e2360170cd36a1115512b778523a73/src/streamer.cpp#L482-L525

You are doing something wrong in your code if it isn't being called. Those area callbacks are called whatever you do (well, not called if you leave I think). So they surely get called even after a ```SetPlayerPos```.
