### ISSUE TITLE
NPCs cause actor streaming to break (2.9.2)

### ISSUE THREAD

**Issue by TommyB123** [samp-incognito/samp-streamer-plugin#242]
Hey there.

I noticed after updating to 2.9.2 actor streaming ceased to work. After some debugging, I discovered that [haveAllPlayersCheckedActors](https://github.com/samp-incognito/samp-streamer-plugin/blob/master/src/utility/misc.cpp#L410) always returns false when an NPC is connected.

**Comment by IstuntmanI** [comment]
After thinking a bit, looks like this bug is actually because of me, again :sweat_smile: :
https://github.com/samp-incognito/samp-streamer-plugin/commit/0edf1da751d9bd642883e6b6ddfcef76aa97412e

In `discoverActors` we have:
https://github.com/samp-incognito/samp-streamer-plugin/blob/aca8a0369425a8975244a647c55653e33ff7b9c3/src/streamer.cpp#L739
but because that function won't be called, the NPC player will have that function kept as false. What I can think of right now is to keep all this code:
https://github.com/samp-incognito/samp-streamer-plugin/blob/aca8a0369425a8975244a647c55653e33ff7b9c3/src/streamer.cpp#L717-L738
in a
```cpp
if(sampgdk::IsPlayerNPC(player.playerID))
```
check instead.
