### ISSUE TITLE
RW-MP team

### ISSUE THREAD

**Issue by TheLunix** [samp-incognito/samp-streamer-plugin#284]
Greetings. I am one of the testers of the new multiplayer for GTA SA and came with a request to adapt your plug-in for us. I know for the time being little known, but I would very much like to see your plug-in with us. I will leave a link to the forum, you will suddenly find it interesting to read http://forum.rw-mp.net/index.php With all the best from rw-mp team

**Comment by IstuntmanI** [comment]
RW-MP is started from the leaked SA-MP 0.2x or 0.2.5, still trying to copy SA-MP. SA-MP is miles ahead of RW-MP. It would require tons of changes to make this plugin compatible with your multiplayer mod. Most of the changes required would be to remove tons of functions if they aren't actually existing.

Also, the player base of RW-MP is basically non existent and it has no chances to go any further than that. You started a multiplayer mod in 2017(?) for a game released in 2005 for Windows, when there are already two huge multiplayers (SA-MP and MTA) that are pretty stable (well, SA-MP has tons of bugs).

I don't want this plugin to support a copycat.

Also, instead of creating a multiplayer from a leaked source and trying to copy the original, wouldn't it be better for you to create something like [SA-MP+](http://forum.sa-mp.com/showthread.php?t=520666) ? An additional client and plugin for SA-MP would be far better and would increase the adoption rate.

**Comment by BigETI** [comment]
I don't think that there is a great need to adopt this for RW:MP, as you're using code that were never permitted to be distributed to the public, infact it is a crime to do so. However if you want to come up with a solution to your problem, then you can create a fork out of it and make your changes. After all this is an open-source project. If you don't want to go this way, you can revert to a version that is compatible with SA:MP 0.2.X and your fork from stolen SA:MP source code, or leave it as it is.

**Comment by kurta999** [comment]
This game is more thatn 10 years old, we should forget it :D
