### ISSUE TITLE
Loading filterscripts gets progressivly slower when the streamer is loaded

### ISSUE THREAD

**Issue by arfni** [samp-incognito/samp-streamer-plugin#294]
Hello,

My server relies on filterscripts being constantly loaded and unloaded, I've noticed it gets progressively slower over time and done some testing.

Loading filterscripts with the streamer:
https://pastebin.com/sPgybsE2

Loading filterscripts without the streamer:
https://pastebin.com/kUsdiTEL

The filterscripts look like this:

```
#include <a_samp>
#define FILEPOINTER "Wzc0M11bQ29vbCBEcmVhbXMgSUld"

// [ V A R I A B L E S ]
new Velocity_1;
// [ - - - - - - - - - ]

forward OnPlayerEnterMarker(playerid, markerid);
public OnPlayerEnterMarker(playerid, markerid)
{
    if (markerid == Velocity_1)
        CallRemoteFunction("SetPlayerVehiclePosition", "iffffff", playerid, 5889.1000976563, -5905.7001953125, 91.900001525879, 0.0, 0.0, 180.0);
    return true;
}

forward LoadMapFilterscript(gamemodeid, filepointer[]);
public LoadMapFilterscript(gamemodeid, filepointer[])
{
    if (strcmp(filepointer, FILEPOINTER, false)) return false;

    // CallRemoteFunction("CreateModeMarker", "fffsfiiiii", X, Y, Z, "corona", size, r, g, b, a, gamemodeid);
    Velocity_1 = CallRemoteFunction("CreateModeMarker", "fffsfiiiii", 6768.1000976563, 354.70001220703, 32.200000762939, "corona", 3.5, 0, 0, 0, 0, gamemodeid);
    return true;
}
```

**Comment by Southclaws** [comment]
You might want to check this thread out: http://forum.sa-mp.com/showthread.php?p=4029291

I have no idea if this is related but since you mentioned you make heavy use of loading and unloading filterscripts, I thought I should let you know about this bug.

**Comment by IstuntmanI** [comment]
Confirmed. Tested with Streamer Plugin v2.7.7, v2.9.2 and v2.9.3, it gets progressively with any version.

```c
new lTick;

for( new i = 0; i < 500; i ++ )
{
    lTick = GetTickCount( );
    SendRconCommand( "loadfs FSNAME" );
    printf( "Loaded in %dms", GetTickCount( ) - lTick );
    SendRconCommand( "unloadfs FSNAME" );
}
```

Well, I tried to start debugging this thing, but I can't even generate the files with CMake on Windows with all these new steps of compiling the Streamer Plugin (basically, I can't compile boost so CMake won't recognize it), it was perfect with the old way of directly cloning & building. 😞

I guess that the problem comes from the loop in the `Utility::checkInterfaceAndRegisterNatives` function, but I can't test that.
https://github.com/samp-incognito/samp-streamer-plugin/blob/420a601401f25de824594173c923d2856ac1f6cd/src/utility/amx.cpp#L30-L84

**Comment by samp-incognito** [comment]
I was curious about this and tested some of the earlier versions. Interestingly, 2.7.0 seemed to be unaffected. The problem cropped up in 2.7.1. The only major change in that version was an sampgdk update, so I built the sampgdk helloworld plugin and tested it just now. The filterscripts began to load progressively slower again when that plugin was loaded.

The memory usage continues to increase as this happens (which does not occur when the helloworld plugin is unloaded), so it looks like some kind of memory leak in sampgdk to me. I might try running it in Valgrind later to see what's going on, but your question might be better directed towards the sampgdk repo in the meantime.

> Well, I tried to start debugging this thing, but I can't even generate the files with CMake on Windows with all these new steps of compiling the Streamer Plugin (basically, I can't compile boost so CMake won't recognize it), it was perfect with the old way of directly cloning & building. 😞

What's your issue exactly? Compiling Boost (or really just Boost.System, which is all that's needed) is easy on Windows: just type `bootstrap` and then `b2 --with-system` on the command line. I guess I could look into making some shell scripts to simplify this for people.

**Comment by arfni** [comment]
@samp-incognito Seems like he fixed it
https://github.com/Zeex/sampgdk/commit/3e0346c020c23535dd6ad6f08e171c776f50211b

**Comment by samp-incognito** [comment]
Nice, I'll update the files.

**Comment by IstuntmanI** [comment]
>What's your issue exactly? Compiling Boost (or really just Boost.System, which is all that's needed) is easy on Windows: just type bootstrap and then b2 --with-system on the command line. I guess I could look into making some shell scripts to simplify this for people.

I guess that the problem is somewhere between executing the `bootstrap.bat` file and trying to compile the Boost.System with the "`b2 --with-system`". Executing `bootstrap.bat` with no additional arguments tells that it couldn't detect the location of the Visual Studio compiler:
```
could not find "vswhere"
###
### "Could not find a suitable toolset."
###
### You can specify the toolset as the argument, i.e.:
###     .\build.bat msvc
###
### Toolsets supported by this script are: borland, como, gcc,
###     gcc-nocygwin, intel-win32, metrowerks, mingw, msvc, vc7, vc8,
###     vc9, vc10, vc11, vc12, vc14, vc141
###
### If you have Visual Studio 2017 installed you will need either update
### the Visual Studio 2017 installer or run from VS 2017 Command Prompt
### as we where unable to detect your toolset installation.
###
```

Even if that "vswhere" thing comes [preinstalled with Visual Studio 2017](https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/), but I guess that isn't added to the `PATH` by default. When manually specifying vc141 or msvc as an argument, like `bootstrap msvc`, looks like it works fine, but then, when executing "`b2 --with-system`, I see this: "`error: wrong library name 'system' in the --with-<library> option.`". Which is pretty weird, because I executed "`git submodule update --init --recursive`" before, but all I see in the "`boost\libs\system`" folder is a "`.git`" file with "`gitdir: ../../../../.git/modules/lib/boost/modules/system`" in it (it has few folders and files in it). Initially cloned the repo with GitKraken and pressed ok when it asked me to initiate the submodules.

This is what I get if I executed `b2` directly:
```
Performing configuration checks

    - default address-model    : 32-bit
    - default architecture     : x86

Building the Boost C++ Libraries.


    - symlinks supported       : no
    - junctions supported      : yes
    - hardlinks supported      : yes
error: Unable to find file or target named
error:     '/boost/system//boost_system'
error: referred to from project at
error:     'libs/chrono/build'
error: could not resolve project reference '/boost/system'
```

Also, if ignoring the problems and continuing to execute "`cmake ..`" in the "`build`" folder I get these errors, which is pretty normal I guess:
```
-- cotire 1.8.0 loaded.
-- C CXX RC target streamer cotired.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory ../samp-streamer-plugin
   used as include directory in directory ../samp-streamer-plugin
   used as include directory in directory ../samp-streamer-plugin/src
   used as include directory in directory ../samp-streamer-plugin/src
   used as include directory in directory ../samp-streamer-plugin/src
   used as include directory in directory ../samp-streamer-plugin/src
   used as include directory in directory ../samp-streamer-plugin/src
   used as include directory in directory ../samp-streamer-plugin/src
   used as include directory in directory ../samp-streamer-plugin/src/manipulation
   used as include directory in directory ../samp-streamer-plugin/src/manipulation
   used as include directory in directory ../samp-streamer-plugin/src/natives
   used as include directory in directory ../samp-streamer-plugin/src/natives
   used as include directory in directory ../samp-streamer-plugin/src/utility
   used as include directory in directory ../samp-streamer-plugin/src/utility

-- Configuring incomplete, errors occurred!
See also "../samp-streamer-plugin/build/CMakeFiles/CMakeOutput.log".
See also "../samp-streamer-plugin/build/CMakeFiles/CMakeError.log".
```

Also, I don't like CMake because it creates tons of garbage files.
The whole process is slow. The way it was before, with Premake and having the "submodules" directly in the repository was direct clone & build.

**Comment by IstuntmanI** [comment]
Looks like the submodules update stage (`git submodule update --init --recursive`) wasn't executed correctly. I deleted the old folder and manually cloned the repository exactly like in the compilation guide on the wiki. The folder of the "`system`" library now has the correct files in there. It has been compiled successfully.

Still, the whole process is pretty slow. But looks like the compiling goes faster now.

**Comment by samp-incognito** [comment]
You also have the option of just installing Boost elsewhere and either putting it in your PATH or specifying the location with CMake. This saves a lot of time.

And yes, Cotire (a CMake module) has speed up the compilation time quite a bit through unity builds.
