### ISSUE TITLE
CreateDynamicMapIcon

### ISSUE THREAD

**Issue by Tagoff** [samp-incognito/samp-streamer-plugin#311]
I would like to show a global map icon for just a player, like a GPS etc. But i'm not sure if is correct to use the stream distance even i used the MAPICON_GLOBAL tag.
Syntax:
`CreateDynamicMapIcon(Float:x, Float:y, Float:z, type, color, worldid = -1, interiorid = -1, playerid = -1, Float:**STREAMERDISTANCE** = STREAMER_MAP_ICON_SD, **STYLE** = MAPICON_LOCAL[, areaid = -1, priority = 0)`

Code:
PS: Look at the 9999.0 and the tag MAPICON_GLOBAL.
`PROP[propid][pD_MapIcon] = CreateDynamicMapIcon(PROP[propid][pD_X], PROP[propid][pD_Y], PROP[propid][pD_Z], 35, 1, -1, -1, playerid, **9999.0**, **MAPICON_GLOBAL**, -1, 0);	`

I'm using the that MAPICON_GLOBAL, why do i need to specify the streamer distance? is correct using 9999.0 ? even with MAPICON_GLOBAL? what is the correct way?

There is any diference using the MAPICON_GLOBAL to MAPICON_LOCAL if u just show by the streamer distance?

**Comment by IstuntmanI** [comment]
The style is handled by the client, while the `streamdistance` is handled by the Streamer Plugin. To make an item appear from any point on the map, simply use a negative streaming distance, which is perfect for `MAPICON_GLOBAL`.

If you use `streamdistance = -1.0` and `style = MAPICON_GLOBAL`, it will be streamed all the time (`SetPlayerMapIcon` applied internally) and seen from everywhere.
If you use `streamdistance = -1.0` and `style = MAPICON_LOCAL`, it will be streamed all the time, but it will appear only when you will be in the range of it, because there's when the game will draw it on radar.
If you use `streamdistance = 300.0` and `style = MAPICON_GLOBAL`, it will be streamed only when you are in the range of 300.0 units to it and it will appear instantly, because it is a global one.
Also, if you are using a `streamdistance` bigger than the set cellsize (or celldistance, not sure which one), then it will have the same effect as `streamdistance = -1.0`, because the Streamer Plugin will set it to stream from any point on the map.

So, think of it like some kind of priority checking: first is streaming distance (if it is successfully fulfilled then the Streamer Plugin will apply the correct internal function - `SetPlayerMapIcon` in this case), then it is the game that decides whether to draw it or not.
