### ISSUE TITLE
Extra Item Identification

### ISSUE THREAD

**Issue by MuthaX** [samp-incognito/samp-streamer-plugin#313]
Yeah, i know there is E_STREAMER_EXTRA_ID and it can be used as array for any purpose.

I suggest to add another "extra"-variable.
It is often need to implement item identification that can be accessed directly to determine that item assigned to "system:somesystem" / "database_table_id" and to some ID (E_STREAMER_EXTRA_ID) in that system/list.

It is will be useful where you need infinity number of items (no need to allocate big arrays in scripts) and operative select methods in interaction with items.

**Comment by Fleynaro** [comment]
support the idea. It would be very good to access dynamic variables of a dynamic object,

**Comment by IstuntmanI** [comment]
`E_STREAMER_EXTRA_ID` can easily do that because, as you said, it can be used as an array. You can create a standard for all of your items.

We'll take as an example items ("furniture") that can be placed by players in their houses. The first index in the array could be occupied by the "system" ID (an unique ID to represent the houses). You can easily create an enumeration for that, like `enum STREAMER_SYSTEM_ID { HOUSE, BUSINESS, GANG, JOB, SHOP, PLAYER }`.
The second one could use a more specific ID in that system, that being the house ID.
The third one be the slot ID of the house where the current item is placed in.
So, if the first index's value is set as the value of `STREAMER_SYSTEMS:HOUSE`, then it would mean that the object always has at least 3 indexes set, so you can check them like
```pawn
if( lExtraID[ 0 ] == STREAMER_SYSTEMS:HOUSE )
{
    new lHouseID = lExtraID[ 1 ], lSlotID = lExtraID[ 2 ];
    // things
}
```

A new ID array for "identification" would be exactly the same thing. That's the main goal of streamer's extra ID anyway.

You could also create and use a helper function like
```pawn
enum
{
	SYSTEM_HOUSE,
	SYSTEM_BUSINESS,
	SYSTEM_GANG,
	SYSTEM_JOB,
	SYSTEM_SHOP,
	SYSTEM_PLAYER
}

stock SetHouseItemData( houseid, houseitemslot, itemtype, STREAMER_ALL_TAGS:itemid )
{
	new arr[ 3 ];
	arr[ 0 ] = _:SYSTEM_HOUSE;
	arr[ 1 ] = houseid;
	arr[ 2 ] = houseitemslot;

	Streamer_SetArrayData( itemtype, itemid, E_STREAMER_EXTRA_ID, arr );
}

//

new
	houseid = 100,
	houseitemslot = 1,
	STREAMER_TAG_OBJECT objectid = CreateDynamicObject( 1000, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 );

SetHouseItemData( houseid, houseitemslot, STREAMER_TYPE_OBJECT, objectid );
```

**Comment by WheneverRide** [comment]
Yeah I know that (and use it already).
The question is in direct access to elements of E_STREAMER_EXTRA_ID-array.
It would be good to have functions like: 
```
Streamer_GetArrayDataElement(type, id, data, dest[], array_index);
Streamer_SetArrayDataElement(type, id, data, dest[], array_index, value);
```
... for direct access and manipulate.
It is heavy to use on over 1kk items (in loop) Streamer_GetArrayData to get only one variable from E_STREAMER_EXTRA_ID where that array can consist of many elements.

I know that it is possible to use Streamer_GetArrayDataLength to filter some of items because some systems can have different array sizes.

**Comment by samp-incognito** [comment]
Supported now with `E_STREAMER_CUSTOM(x)`.
