### ISSUE TITLE
Slow streaming of pickups and actors

### ISSUE THREAD

**Issue by RodrigoMSR** [samp-incognito/samp-streamer-plugin#373]
I use dynamic pickups and dynamic actors inside interiors, each item has an array of virtual worlds, less than 30 worlds per item. Sometimes it can take up to 10 seconds for them to appear, other times it is almost instantaneous. The server's tick rate is 80-100 (200 players).

Video: https://youtu.be/wCa0zvTyMLE

**Comment by Chaprnks** [comment]
It's been a while since I've used the streamer plugin, but I think your issue is the tick rate. If I'm remembering correctly, the default tick rate is around 40-60; maybe you can reset it back to default, to see if that fixes it. Also, I'd suggest looking into the stream rate on the sa-mp server as a whole (inside server.cfg). That also could play a factor in the objects streaming in with a delay

**Comment by RodrigoMSR** [comment]
This problem does NOT occur with objects, 3D labels, checkpoints or other types of items, only with actors and pickups. In the video, the dynamic 3D text label appears 10 seconds before the actor and the pickup.

It doesn't make much sense to lower the tickrate (slow down the server) to resolve this. I use sleep 5 in server.cfg, which is the default.

**Comment by RodrigoMSR** [comment]
I've downloaded build from this commit:
https://github.com/samp-incognito/samp-streamer-plugin/commit/00023639ceccfd30cc8e7562d12888d57f4c55c9

And fixed the problem.
