### ISSUE TITLE
BUG with DynamicCP

### ISSUE THREAD

**Issue by KrYpToDeN** [samp-incognito/samp-streamer-plugin#39]
Incognito, please check my post №4937 on sa-mp.com
http://forum.sa-mp.com/showpost.php?p=3348078&postcount=4937

I probably found bad BUG in DynamicCP. 
It can move with player:D

Thank you.

**Comment by samp-incognito** [comment]
The checkpoint is most likely "moving" because you created two right next to each other. If you move closer to one checkpoint, the other will disappear because only one can be visible at a time.

As for the checkpoint sizes being incorrect, that's an old GTA/SA-MP bug and can't be fixed through scripting (to my knowledge).

**Comment by KrYpToDeN** [comment]
oh, its my fault from another system while testing.
Thank you!
