### ISSUE TITLE
libmysqlclient.so.18: cannot open shared object file

### ISSUE THREAD

**Issue by L1R26** [samp-incognito/samp-streamer-plugin#403]
Hello

I am getting this issue when trying to run the server with this plugin(last version).
`Failed (libmysqlclient.so.18: cannot open shared object file: No such file or directory)`
Debian10 OS

**Comment by TemaSM** [comment]
@Lamezy Not related to samp-streamer plugin. Checkout your mysql plugin, because it's place where `libmysqlclient.so.18` loading as shared library.

If you cannot install mysql-client on your system by hands, here's ready to use file for you, Place it to root of your server, just right near samp03svr:
[libmysqlclient.so.zip](https://github.com/samp-incognito/samp-streamer-plugin/files/7445340/libmysqlclient.so.zip)

**Comment by alextwothousand** [comment]
This is unrelated to streamer.
The ideal fix would be to install the mariadb/mysql redistributables, but you can also use the static build of mysql (mysql_static.so).
