### ISSUE TITLE
AttachCameraToDynamicObject - object must be streamed, improve it

### ISSUE THREAD

**Issue by kurta999** [samp-incognito/samp-streamer-plugin#49]
Now AFAIK, if you want to attach your camera to dynamic object, then dynamic object needs to be steramed or nothing will happen. 

Somehow would be good to fix this problem.

**Comment by samp-incognito** [comment]
Maybe add a setting to make objects steam based on the player's current camera position (via GetPlayerCameraPos)?

**Comment by kurta999** [comment]
Ohh yes... Camera position only updated frequently when player hold RMB.

**Comment by Kar2k** [comment]
The camera positions are updated faster while moving the mouse (aka the camera). While not moving the position updating slows down. You shouldn't worry about the wiki.. some people put wrong stuff on that thing.

**Comment by samp-incognito** [comment]
Okay. Also, I suppose this wouldn't exactly solve the problem of the camera not attaching because of the object not being streamed initially, but it would be useful if the object is moving. The only way to fix this, then, is to force an update beforehand, which could be done internally, I suppose. The object might immediately stream out again, though, if the player is nowhere near the object. That could also be remedied by using camera positions rather than player positions. Does anyone know if this could be automatically detected by using GetPlayerState, GetCameraMode, or something similar? Otherwise, the script will have to manually specify when it's appropriate to use camera positions.

**Comment by Kar2k** [comment]
Erm. On this weird note. Since when does the object has to be streamed in? Look at the wiki example (http://wiki.sa-mp.com/wiki/AttachCameraToPlayerObject). Test that far away from 0.0.0 it will work.

**Comment by ikkentim** [comment]
@Kar2k streamed in by the streamer?

**Comment by ikkentim** [comment]
Maybe create a function which forces a certain object to be streamed for a certain player. Add at as a native as well. I guess that would fix this and it adds a useful function.

**Comment by Crayder** [comment]
Why not just make that specific objects stream distance a lot higher?

**Comment by samp-incognito** [comment]
@ikkentim: You can already do that by setting a negative streaming distance (see #36). I suppose what I could also do is add a native that allows you to easily toggle it (e.g., when it's toggled on, set a negative streaming distance, and when it's toggled off, restore the old streaming distance).
