### ISSUE TITLE
[Enhance] Area parameter on CreateDynamic*

### ISSUE THREAD

**Issue by Crayder** [samp-incognito/samp-streamer-plugin#71]
It's pretty self explanatory but basically what I want to see is a area parameter on CreateDynamic* that would only stream the object to players who are in that specific area.

**Comment by IstuntmanI** [comment]
I don't really see why it would be more useful than the normal streamdistance, could you give an example for the usage ?

**Comment by Crayder** [comment]
That's precisely the problem.
For example, this building:
![image](https://cloud.githubusercontent.com/assets/9919010/9479333/eaefdd5c-4b4a-11e5-91f5-dc414a68fd73.png)
![image](https://cloud.githubusercontent.com/assets/9919010/9479335/ee1b66c2-4b4a-11e5-8e8c-766ec475213d.png)

Say you had hundreds of objects on each floor, each floor the same as the next. Now if you stood on a floor and relied on stream distance to see objects you could easily max out, but if you streamed the objects by floor you would be able to see the required objects. Another case would be interiors (not necessarily their indexes).

**Comment by IstuntmanI** [comment]
I see, your idea is pretty smart.

**Comment by JernejL** [comment]
This is not a bad idea, i guess the scripters and designers could pre-prepare optimal areas and tie objects to them, it would be much more optimal for things that crayder shows (building floors) and possibly other things - like if you want one area to stream as whole, you could just set up a area and add all objects into it with max streaming range, then they would still load only when you enter the zone.

**Comment by RoyEarle** [comment]
So, guys, will Areas be implemented?

**Comment by Crayder** [comment]
Obviously it's being considered, or Incognito would've closed this issue by now. So let's just leave it at that and not pester the guy.

**Comment by samp-incognito** [comment]
I've not tested this at all, but it's in the latest commit.

**Comment by Crayder** [comment]
Thanks, this will be put to great use!

**Comment by RoyEarle** [comment]
Hello.
I've got this while compiling
[streamer.txt](https://github.com/samp-incognito/samp-streamer-plugin/files/111188/streamer.txt)

**Comment by samp-incognito** [comment]
Could you try it again?

**Comment by RoyEarle** [comment]
Sure. Now it's ok.
Where can  I find include file for the last version?

**Comment by Crayder** [comment]
You can just add a "STREAMER_TYPE_AREA area" parameter to the create functions. The extended functions aren't the same , but for the rest it's that simple.

**Comment by samp-incognito** [comment]
Here's my latest copy (change the extension to .inc): [streamer.txt](https://github.com/samp-incognito/samp-streamer-plugin/files/111470/streamer.txt)

**Comment by RoyEarle** [comment]
Tested with one of my interiors.
Working correctly, and if I'll destroy Dynamic Area - objects will disappear.
Have no idea how to run any tests, so here is a question: in theory, creating lots of objects in one place with area parameter will make streamer work faster? Because I remember, as Incognito said, that using worldid and interiorid has the opposite result, if we are talking about optimization.

Sorry for my English. =)

**Comment by RoyEarle** [comment]
And one more question: with area id, streamdistance and drawdistance are still useful?

**Comment by Crayder** [comment]
Everything still has it's own uses. This add-on is just that, another thing you can use. It's not meant to replace everything else and it can't.

**Comment by RoyEarle** [comment]
But what about optimization?

**Comment by samp-incognito** [comment]
Thanks for testing.

I've not run any tests myself, but I doubt it would be more efficient to assign the objects to areas. At best, you'd be bypassing distance checks for those objects, but the plugin would still have to do lookups to see if players are in the correct area(s), which is equally processor-intensive (and, of course, as with interiors and virtual worlds, the more assigned to an object, the less efficient it will be, although just assigning one area would have a pretty negligible cost).

At best, it's probably no better than just using a low streaming distance, but this does give you more control over which objects you want to be visible, so I'd say it's more useful. (The streaming distance, by the way, won't kick in until the player enters the area, so use what you'd like, but don't make it too large unless you need it to be, otherwise it won't be spatially indexed.)

That ended up being longer than I wanted, but I'll probably put some of this on the wiki.

**Comment by RoyEarle** [comment]
But may be just just check if player is in area and don't check the distance between player and object/pickup etc?

**Comment by Crayder** [comment]
> But may be just just check if player is in area and don't check the distance between player and object/pickup etc?

Yeah, perhaps a toggle. Like using '0.0' for the distance. Or maybe even the current negative distance for 'static' objects (which I still don't really understand) would be just fine.

**Comment by samp-incognito** [comment]
Specifying a negative streaming distance would actually do just that. The distance check for that object would be omitted. I hadn't actually thought of that, but it wouldn't be a bad idea at all in this case. It would be slightly more efficient since the streamer would just be doing a single distance check for the area rather than multiple checks for each object.

**Comment by RoyEarle** [comment]
Thanks! And what about drawdistance?

**Comment by samp-incognito** [comment]
Whatever you want it to be. It doesn't impact the streamer's performance. You can just leave it at 0.0.

**Comment by RoyEarle** [comment]
Just great =) Thank you
