### ISSUE TITLE
OnPlayerShootDynamicObject return

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#73]
In OnPlayerShootDynamicObject there is no handler to return 1 / 0 to original sa-mp OnPlayerWeaponShot callback - making desyncing bullets that hit dynamic objects impossible. 
 
https://wiki.sa-mp.com/wiki/OnPlayerWeaponShot
 
Return Values:
0 - Prevent the bullet from causing damage.
1 - Allow the bullet to cause damage.

**Comment by Crayder** [comment]
But... Why would you want to desync a bullet that hit an object?

**Comment by Patrik356b** [comment]
Maybe he want it to be invincible for X seconds and then destructible?.

**Comment by Crayder** [comment]
It's an object, not a player. I don't understand. You can't desync a bullet that has hit an object. 

This callbacks sync is player to player, server to player, and player to server. The server handles the object's data server-sidedly and syncs that data to the players. The players use that data client-sidedly. If he is trying to desync the bullets that are hitting dynamic (by dynamic I mean breakable and such) objects and breaking them, that won't work because the break is client-sided for as long as the object remains streamed in for that one player. Dynamic object client-sided actions are not synced to other players or the server. 

If I've got his idea completely wrong then my bad.

**Comment by JernejL** [comment]
Because cheaters can spam bullets to make it seem like they hit 50 objects at once.. that produces quite a visual particle-flying spectatle depending on object's material.. It's a matter of preventing really retarded glitches caused by cheaters that make game look bad to others - just imagine a shooting range with 50 of those shooting range target body part.. if they shoot all of them at once, each will explode into dozen particles. Plus, they would break the objects on other clients' games since they are >dynamic objects< which break when getting shot at by bullets - and other players wouldn't be able to shoot them even if i don't destroy the objects on server.. the only workaround being to re-create the object which would be quite a heavy workaround for something like that sa-mp support internally so this feature is very much needed in streamer aswell. 
 
So imagine a cheater shooting 50 objects at once and then imagine server trying to compensate for it by re-creating 50 objects.. and then the cheater doing it all over again as long as they want producing glitchyness and extra load on the server.. sadly, this happens daily in sa-mp and this kind of protection is needed - this is just fixed by supporting returning 1 / 0 in the callback and sending it to sa-mp via sampgdk.
