### ISSUE TITLE
2.7.6 and above seem unstable

### ISSUE THREAD

**Issue by Kar2k** [samp-incognito/samp-streamer-plugin#99]
This is just an issue to look into. I have no real proof right now. Nothing to hurt your head about.. I just want some feedback from other developers for now.

But I've went ahead and tried every version after 2.7.6. I've had to end up reverting back to 2.7.4 (I was on 2.7.5.2 for awhile that seemed fine but 2.7.4 seems the best). Whenever I do it my server tends to crash pretty often, like it can't last 3-6 hours without a crash. v2.7.7-v2.7.9 is very crashy. Every version I have HAD to revert the same day. I'm not sure if this is the result of a sampgdk update or all these area updates that you've been adding but AFAIK 2.7.9 is really crashy. If anyone has any insight on why this could be happening please see it be and post. I haven't really debugged anything, I've messaged some other developers and they seem to stick to 2.7.4 because it runs stable and see no need to update. I don't really have a need to update either but I just want to make this discussion. If anyone is using 2.7.6+ and it is stable for them, your comments will be helpful too.

OS: Debian 7 (Linux).

**Comment by Crayder** [comment]
Stable. WinXP and Win7, same machine.

**Comment by Kar2k** [comment]
Crashdetect does not work for me anymore on linux. I've stopped depending on that. ;\

I haven't had any issues on windows... as I don't have a server on windows with alot of players to test.

**Comment by samp-incognito** [comment]
I can't really do anything without a backtrace. Have you tried compiling a debug version and running the server with GDB?

As far as I know, several server owners have been running the latest versions, and no one has reported anything like this.

**Comment by Runn3r** [comment]
I don't have any proof but all i can say is that i have noticed some issues too.

I spawn a object with light (a roadblock) and it dissappears with no actual reason? Like it simply dissapears and it becomes invisible. I spawn a normal object it doesn't despawn works great.

I saw same issues on emmets south central gm.. Objects despawning and dissappearing without no actual reason.

**Comment by Crayder** [comment]
>since i'm now on 2.7.8..

Yet, v2.8 is out.

**Comment by Runn3r** [comment]
Welp why should i use it if i have issues on this one and had on newer versions.

**Comment by Crayder** [comment]
>why should i use it if i have issues on this one
Obviously because it's a new version, which may have fixes for those issues.

>had on newer versions
You've had this problem on versions NEWER than 2.8? Haha, don't think so. 2.8 is the latest after all.

**Comment by Runn3r** [comment]
Newer than 2.7.8 -.-

**Comment by Crayder** [comment]
>Newer than 2.7.8 -.-

Which would then contradict your first comment. So again, use 2.8.

**Comment by Runn3r** [comment]
:facepalm:
I've just told you that i have more issues with the versions above 2.7.8 (including 2.8) and that something is wrong and i don't know what and that's why i'm here trying to figure it out. Don't be a dick if you don't want to help leave.

**Comment by Crayder** [comment]
>(including 2.8)

You haven't clarified that you were using 2.8 before. So no, I wasn't being a dick. I was suggesting that you DO use 2.8.

And like Incognito mentioned, I haven't encountered any of these problems. In fact, I don't think I recall every having any streamer crashes (i.e. despite the ones I've had when personally editing the plugin).

**Comment by Runn3r** [comment]
Well some people do some don't it happens sometimes. It doesn't mean if it works for you it will work for everyone else.

**Comment by Kar2k** [comment]
Dude this issue thread is about crashes not your objects disappearing, make your own issue and don't hog mine.

**Comment by IstuntmanI** [comment]
Is this still a problem for you ? At me the latest plugin version works without any crash related to it. Maybe you use some outdated/buggy plugins ? Yes, probably it is related to sampgdk. AFAIK, plugins which use an older sampgdk have some problems with plugins which use newer sampgdk versions.

This issue should be closed if it is ok now.

**Comment by Kar2k** [comment]
No not just yet, I've switched to Ubuntu Trusty Tahr so I will test it on that.

AFAIK the plugins that use sampgdk on my server is streamer only.

When I switched to Ubuntu, my IRC bots stopped randomly disconnecting, I have NO idea why (That's a thing to note. It's like almost every issue got squashed after switching to Ubuntu.

"streamer274 mysql irc sscanf Whirlpool MapAndreas nativechecker" That is what I use currently so streamer is the only sampgdk plugin?

I will test and get back to you guys.

**Comment by samp-incognito** [comment]
Updates on this? It sounds like it was just some problem with your system.

**Comment by Southclaw** [comment]
Side note: you shouldn't need to run nativechecker in production/public!
It might be worth running a testing server with various plugin combinations but I'm not sure how you could automate activating the streamer (NPC teleporting around the map maybe?) it'll be a tough one to test. Another way to test would be to remove the streamer and switch to one of those Pawn streamers (if they still exist!) temporarily and see if the crashes continue.

**Comment by Patrik356b** [comment]
I doubt teleporting a npc around would affect the streamer. You could try with a custom command to teleport a player around the map though. 

Npcs use either recordings and/or dummy animations and this is applied with certain rotational data as well as the position.

Though nothing needs to be rendered on the npc side really as the collision checking is done on the player side of sa-mp.

The npc plugin that unfortunately went down the wrong way would overcome this since it could render a "player bot". 
 (not looking to start a discussion on that)


At least this is how it used to work. I'm not sure how lagcomp affects this but the lagcomp iirc does allow different things depending on if the setting is off/on. 
(afaik it affected if the npc could hurt player or if the player could hurt the npc)

**Comment by Patrik356b** [comment]
I don't know how how the npcs handles areas though. That is the only thing that might be rendered for the npc as that would make the most sense. 
This applies to gangzones and checkpoints/racecheckpoints/pickups

**Comment by Southclaw** [comment]
What I meant was to try and trigger the problems in an automated fashion by using an NPC to stream in objects (it wouldn't matter that the CreateObject calls wouldn't do anything if it's an internal streamer code issue).

**Comment by Patrik356b** [comment]
Then the option would be to teleport into and out of an area like those defined above. This should work but I haven't tested this method

**Comment by samp-incognito** [comment]
Object streaming for NPCs is disabled in the plugin to save resources, but checkpoints/pickups/areas are still processed so that any callbacks can be triggered for them.

If you did want to simulate a full server using NPCs, you'd just need to remove the IsPlayerNPC checks from the plugin and recompile. I've never tested this, though. I'm actually not even sure if every native the plugin uses will work with NPC IDs. I know that GetPlayerPos works, at least.

**Comment by karimcambridge** [comment]
NPC's handle areas pretty good. I use them. Please don't randomly remove that feature ever lol.

Anyway, the latest 2.8.2 is great. I put it up from 2.7.4 and my server hasn't even crashed since.

There we're alot of area crashes and stuff between 2.7.4 - 2.7.x thats why it was probably so unstable for me then.

Thanks!
